[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 8888
  framework = "vite"
  autoLaunch = false

# 🔒 Redirect any accidental ngrok traffic to your live backend
[[redirects]]
from = "/*"
to = "https://tsc-backend-v2.onrender.com/:splat"
status = 301
conditions = { Host = ["*.ngrok-free.app", "*.ngrok.io"] }

# ✅ Proper API routing for dev & prod
[[redirects]]
from = "/api/*"
to   = "https://tsc-backend-v2.onrender.com/:splat"
status = 200
force = true

# 🧠 Helpful debug header
[[headers]]
for = "/*"
[headers.values]
X-Backend-Policy = "Redirected from ngrok → Render backend only"