[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 8888
  framework = "vite"
  autoLaunch = false

# Redirect any accidental ngrok traffic to your live backend
[[redirects]]
from = "/*"
to = "https://tsc2025.onrender.com/:splat"
status = 301
conditions = { Host = ["*.ngrok-free.app", "*.ngrok.io"] }

# Proper API routing for dev & prod
[[redirects]]
from = "/api/*"
to   = "https://tsc2025.onrender.com/:splat"
status = 200
force = true

# Helpful header for debugging
[[headers]]
for = "/*"
[headers.values]
X-Backend-Policy = "Only Render backend allowed — ngrok blocked and redirected"