import React from 'react';
import assets from './../assets/assets';

const deputyDirectory = {
    "Lead Female Vocal": [{
            id: "1f3v8aa1",
            firstName: "Shamyra",
            lastName: "Abbott",
            instrument: "Lead Female Vocal",
            image: assets.Shamyra
        },
        {
            id: "1f3v8bb2",
            firstName: "Kedesha",
            lastName: "Charles",
            instrument: "Lead Female Vocal",
            image: assets.Kedesha,
        },
        {
            id: "1f3v8cc3",
            firstName: "Mariam",
            lastName: "S",
            instrument: "Lead Female Vocal",
            image: assets.Mariam,
        }],
    "Lead Male Vocal": [{
            id: "2f3v8aa1",
            firstName: "Rya",
            lastName: "Pink",
            instrument: "Lead Male Vocal",
            image: assets.Rya,
        },
        {
            id: "2f3v8bb2",
            firstName: "Gerhsom",
            lastName: "Brown",
            instrument: "Lead Male Vocal",
            image: assets.Gershom,
        },
        {
            id: "2f3v8cc3",
            firstName: "Torann",
            lastName: "Opara",
            instrument: "Lead Male Vocal",
            image: assets.Torann,
        }],
    "Lead Vocal": [{
        id: "3f3v8aa1",
        firstName: "Kevin",
        lastName: "Fullinck",
        instrument: "Lead Vocal",
        image: assets.Kevin,
    }],
    "MC / Rapper": [{
            id: "2f3v8aa1",
            firstName: "Rya",
            lastName: "Pink",
            instrument: "Lead Male Vocal",
            image: assets.Rya,
        },
        {
            id: "1f3v8bb3",
            firstName: "Emma May",
            lastName: "Osi-Lah",
            instrument: "Lead Female Vocal",
            image: assets.EmmaMay,
        },
        {
            id: "2f3v8cc3",
            firstName: "Torann",
            lastName: "Opara",
            instrument: ["Lead Female Vocal", "MC / Rapper"],
            image: assets.Torann,
        }],
    "Vocalist-Guitarist": [{
            id: "4f3v8aa1",
            firstName: "Sam",
            lastName: "Monoghan",
            instrument: "Vocalist-Guitarist",
            image: assets.Sam,
        },
        {
            id: "4f3v8bb2",
            firstName: "Phoebe",
            lastName: "Belli",
            instrument: "Vocalist-Guitarist",
            image: assets.Phoebe,
        },
        {
            id: "41f3v8cc3",
            firstName: "Jeremy",
            lastName: "Allen",
            instrument: "Vocalist-Guitarist",
            image: assets.Jeremy,
        }],
    "Vocalist-Bassist": [],
    "Bass Guitar": [{
            id: "5f3v8aa1",
            firstName: "Ewan",
            lastName: "McIntosh",
            instrument: "Bass Guitar",
            image: assets.Ewan,
        },
        {
            id: "5f3v8bb2",
            firstName: "Frazer",
            lastName: "Pearce",
            instrument: "Bass Guitar",
            image: assets.Frazer,
        },
        {
            id: "5f3v8cc3",
            firstName: "Marco",
            lastName: "Abbatecola",
            instrument: "Bass Guitar",
            image: assets.Marco,
        }],
    "Electric Guitar": [{
            id: "6f3v8aa1",
            firstName: "Callum",
            lastName: "Garland",
            instrument: "Electric Guitar",
            image: assets.Callum,
        },
        {
            id: "6f3v8bb2",
            firstName: "Chris",
            lastName: "Smith",
            instrument: "Electric Guitar",
            image: assets.Chris,
        },
        {
            id: "6f3v8cc3",
            firstName: "David",
            lastName: "Kirkwood",
            instrument: "Electric Guitar",
            image: assets.David,
        }],
    "Keyboard": [{
            id: "7f3v8aa1",
            firstName: "Renes",
            lastName: "BBWI",
            instrument: "Keyboard",
            image: assets.Renes,
        },
        {
            id: "7f3v8bb2",
            firstName: "Cyrus",
            lastName: "Atkinson",
            instrument: "Keyboard",
            image: assets.Cyrus,
        },
        {
            id: "7f3v8cc3",
            firstName: "David",
            lastName: "Kofi",
            instrument: "Keyboard",
            image: assets.DavidK,
        }],
    "Acoustic Guitar": [],
    "Acoustic Bass": [],
    "Drums": [{
            id: "8f3v8aa1",
            firstName: "Will",
            lastName: "Spurling",
            instrument: "Drums",
            image: assets.Will,
        },
        {
            id: "8f3v8bb2",
            firstName: "Emanuele",
            lastName: "Marchetti",
            instrument: "Drums",
            image: assets.Emanuele,
        },
        {
            id: "8f3v8cc3",
            firstName: "Joe",
            lastName: "Jeffcoate",
            instrument: "Drums",
            image: assets.Joe,
        }],
    "Saxophone": [{
            id: "9f3v8aa1",
            firstName: "Eve",
            lastName: "Ledisi",
            instrument: "Saxophone",
            image: assets.Eve,
        },
        {
            id: "8f3v8bb2",
            firstName: "Nicki",
            lastName: "Hutchins",
            instrument: "Saxophone",
            image: assets.Nicki,
        },
        {
            id: "8f3v8cc3",
            firstName: "Sophie",
            lastName: "Burrows",
            instrument: "Saxophone",
            image: assets.Sophie,
        }],
    "Trumpet": [{
            id: "9f3v8aa1",
            firstName: "Becky",
            lastName: "Waite",
            instrument: "Trumpet",
            image: assets.Becky,
        },
        {
            id: "9f3v8bb2",
            firstName: "Colin",
            lastName: "Jones",
            instrument: "Trumpet",
            image: assets.Colin,
        },
        {
            id: "9f3v8cc3",
            firstName: "Josh",
            lastName: "Betley",
            instrument: "Trumpet",
            image: assets.Josh,
        }],
    "Trombone": [],
    "Double Bass": [],
    "Cello": [],
    "Violin / Fiddle": [],
    "Banjo": [],
    "Mandolin": [],
    "Percussion": [],
    "Cajon": [],
    "Flute": [],
    "Clarinet": [],
};

export default deputyDirectory;
