[
    { "year": 2005, "title": "1 Thing", "artist": "Amerie", "genre": "R&B/Funk" },
    { "year": 1982, "title": "A Night To Remember", "artist": "Shalamar", "genre": "R&B/Post-Disco" },
    { "year": 1999, "title": "Bills Bills Bills", "artist": "Destiny's Child", "genre": "Contemporary R&B" },
    { "year": 2001, "title": "Bootylicious", "artist": "Destiny's Child", "genre": "R&B/Pop" },
    { "year": 1998, "title": "Can't Take My Eyes Off Of You", "artist": "Lauryn Hill", "genre": "R&B/Soul" },
    { "year": 1986, "title": "Control", "artist": "Janet Jackson", "genre": "Contemporary R&B / New Jack Swing" },
    { "year": 2002, "title": "Cry Me a River", "artist": "Justin Timberlake", "genre": "Pop / R&B" },
    { "year": 2011, "title": "End of Time", "artist": "Beyoncé", "genre": "R&B / Pop" },
   { "year": 1998, "title": "Ex-Factor", "artist": "Lauryn Hill", "genre": "R&B / Neo Soul" },
    { "year": 2001, "title": "Fallin'", "artist": "Alicia Keys", "genre": "Neo Soul / R&B" },
    { "year": 2002, "title": "Foolish", "artist": "Ashanti", "genre": "Contemporary R&B" },
    { "year": 2003, "title": "Frontin'", "artist": "Pharrell", "genre": "R&B / Hip Hop Soul" },
    { "year": 2008, "title": "Halo", "artist": "Beyoncé", "genre": "R&B / Pop" },
    { "year": 1999, "title": "Heartbreaker", "artist": "Mariah Carey ft. Jay-Z", "genre": "Contemporary R&B / Pop" },
    { "year": 1993, "title": "Hero", "artist": "Mariah Carey", "genre": "Pop / R&B Ballad" },
    { "year": 2004, "title": "If I Ain't Got You", "artist": "Alicia Keys", "genre": "R&B / Neo-Soul" },
    { "year": 1999, "title": "If You Had My Love", "artist": "Jennifer Lopez", "genre": "Pop / R&B" },
    { "year": 2000, "title": "Independent Women Part I", "artist": "Destiny's Child", "genre": "R&B / Pop" },
    { "year": 1977, "title": "Waterfalls", "artist": "TLC", "genre": "Contemporary R&B" },
    { "year": 2001, "title": "No Scrubs", "artist": "TLC", "genre": "R&B" },
    { "year": 2006, "title": "Rehab", "artist": "Amy Winehouse", "genre": "Soul / R&B" },
    { "year": 2002, "title": "Rock Your Body", "artist": "Justin Timberlake", "genre": "Pop / R&B" },
    { "year": 1999, "title": "Say My Name", "artist": "Destiny's Child", "genre": "Contemporary R&B" },
  { "year": 1998, "title": "The Boy Is Mine", "artist": "Brandy & Monica", "genre": "Contemporary R&B" },
    { "year": 2000, "title": "Independent Women Part I", "artist": "Destiny's Child", "genre": "Contemporary R&B / Pop" },
    { "year": 2000, "title": "Try Again", "artist": "Aaliyah", "genre": "R&B / Hip Hop Soul" },
    { "year": 1999, "title": "U Know What's Up", "artist": "Donell Jones", "genre": "Contemporary R&B" },
    { "year": 2008, "title": "Single Ladies (Put a Ring on It)", "artist": "Beyoncé", "genre": "Contemporary R&B / Pop" },
    { "year": 2006, "title": "Stronger Than Me", "artist": "Amy Winehouse", "genre": "Soul / R&B" },
    { "year": 2001, "title": "Survivor", "artist": "Destiny's Child", "genre": "R&B / Pop" },
    { "year": 1993, "title": "That's the Way Love Goes", "artist": "Janet Jackson", "genre": "Contemporary R&B" },
    { "year": 1998, "title": "The Boy Is Mine", "artist": "Brandy & Monica", "genre": "Contemporary R&B" },
    { "year": 2000, "title": "Try Again", "artist": "Aaliyah", "genre": "R&B / Hip Hop Soul" },
    { "year": 1999, "title": "U Know What's Up", "artist": "Donell Jones", "genre": "Contemporary R&B" },
    { "year": 2001, "title": "Survivor", "artist": "Destiny's Child", "genre": "Contemporary R&B / Pop" },
    { "year": 2003, "title": "Stronger Than Me", "artist": "Amy Winehouse", "genre": "Soul / R&B" },
    { "year": 2008, "title": "Single Ladies (Put a Ring on It)", "artist": "Beyoncé", "genre": "Contemporary R&B / Pop" },
    { "year": 1999, "title": "Say My Name", "artist": "Destiny's Child", "genre": "Contemporary R&B" },
    { "year": 2006, "title": "Rehab", "artist": "Amy Winehouse", "genre": "Soul / R&B" },
    { "year": 2002, "title": "Rock Your Body", "artist": "Justin Timberlake", "genre": "Pop / R&B" },
    { "year": 2008, "title": "Halo", "artist": "Beyoncé", "genre": "Pop / R&B" },
    { "year": 2004, "title": "Lose My Breath", "artist": "Destiny's Child", "genre": "Contemporary R&B" },
    { "year": 2000, "title": "Independent Women Part I", "artist": "Destiny's Child", "genre": "Contemporary R&B / Pop" },
    { "year": 2007, "title": "No One", "artist": "Alicia Keys", "genre": "Contemporary R&B" },
    { "year": 1999, "title": "If You Had My Love", "artist": "Jennifer Lopez", "genre": "Pop / R&B" },
  { "year": 2000, "title": "Independent Women Part I", "artist": "Destiny's Child", "genre": "Contemporary R&B" },
    { "year": 2019, "title": "I Want You Around", "artist": "Snoh Aalegra", "genre": "R&B / Soul" },
    { "year": 2002, "title": "Wish I Didn't Miss You", "artist": "Angie Stone", "genre": "Neo-Soul / R&B" },
    { "year": 2000, "title": "Jumpin' Jumpin'", "artist": "Destiny's Child", "genre": "Contemporary R&B" },
    { "year": 1996, "title": "Killing Me Softly with His Song", "artist": "The Fugees", "genre": "Hip Hop Soul" },
  { "year": 1996, "title": "Kissing You", "artist": "Des'ree", "genre": "R&B / Soul" },
    { "year": 2002, "title": "Like I Love You", "artist": "Justin Timberlake", "genre": "Pop / R&B" },
    { "year": 2001, "title": "Little Things", "artist": "India.Arie", "genre": "Neo-Soul" },
    { "year": 2004, "title": "Lose My Breath", "artist": "Destiny's Child", "genre": "R&B" },
    { "year": 2011, "title": "Love On Top", "artist": "Beyoncé", "genre": "R&B / Pop" },
  { "year": 2012, "title": "Next To Me", "artist": "Emeli Sandé", "genre": "Pop / R&B" },
    { "year": 2007, "title": "No One", "artist": "Alicia Keys", "genre": "R&B / Soul" },
    { "year": 1999, "title": "No Scrubs", "artist": "TLC", "genre": "Contemporary R&B" },
    { "year": 2006, "title": "Rehab", "artist": "Amy Winehouse", "genre": "Soul / R&B" },
    { "year": 2002, "title": "Rock Your Body", "artist": "Justin Timberlake", "genre": "Pop / R&B" },
    { "year": 1999, "title": "Say My Name", "artist": "Destiny's Child", "genre": "Contemporary R&B" },
    { "year": 2003, "title": "Senorita", "artist": "Justin Timberlake", "genre": "Pop / R&B" },
    { "year": 2000, "title": "Shackles (Praise You)", "artist": "Mary Mary", "genre": "Gospel / R&B" },
    { "year": 2008, "title": "Single Ladies (Put a Ring on It)", "artist": "Beyoncé", "genre": "Contemporary R&B / Pop" },
    { "year": 2003, "title": "Stronger Than Me", "artist": "Amy Winehouse", "genre": "Soul / R&B" },
  { "year": 2001, "title": "Survivor", "artist": "Destiny's Child", "genre": "R&B / Pop" },
    { "year": 1993, "title": "That's The Way Love Goes", "artist": "Janet Jackson", "genre": "R&B / Pop" },
    { "year": 1998, "title": "The Boy Is Mine", "artist": "Brandy & Monica", "genre": "R&B" },
    { "year": 2000, "title": "Try Again", "artist": "Aaliyah", "genre": "R&B / Hip Hop" },
    { "year": 1999, "title": "U Know What's Up", "artist": "Donell Jones", "genre": "R&B" },
    { "year": 2006, "title": "Until The End Of Time", "artist": "Beyoncé", "genre": "R&B / Soul" },
    { "year": 2001, "title": "Video", "artist": "India.Arie", "genre": "Neo-Soul / R&B" },
    { "year": 1995, "title": "Waterfalls", "artist": "TLC", "genre": "R&B / Pop" },
    { "year": 1986, "title": "What Have You Done For Me Lately", "artist": "Janet Jackson", "genre": "R&B / Funk" },
    { "year": 1986, "title": "When I Think Of You", "artist": "Janet Jackson", "genre": "R&B / Pop" },
   { "year": 1998, "title": "When You Believe", "artist": "Whitney Houston & Mariah Carey", "genre": "Pop / Gospel" },
    { "year": 2017, "title": "Wild Thoughts", "artist": "DJ Khaled ft Rihanna", "genre": "R&B / Hip Hop" },
    { "year": 2006, "title": "You Know I'm No Good", "artist": "Amy Winehouse", "genre": "Soul / Jazz" },
    { "year": 2000, "title": "Independent Women", "artist": "Destiny's Child", "genre": "R&B / Pop" },
    { "year": 2020, "title": "I Want You Around", "artist": "Snoh Aalegra", "genre": "R&B / Neo-Soul" },
    { "year": 2002, "title": "I Wish I Didn't Miss You Anymore", "artist": "Angie Stone", "genre": "R&B / Soul" },
    { "year": 2001, "title": "Jumpin', Jumpin'", "artist": "Destiny's Child", "genre": "R&B / Pop" },
    { "year": 1996, "title": "Killing Me Softly", "artist": "The Fugees", "genre": "Hip Hop / Soul" },
   { "year": 1982, "title": "A Night To Remember", "artist": "Shalamar", "genre": "R&B / Funk" },
    { "year": 1988, "title": "Don't Be Cruel", "artist": "Bobby Brown", "genre": "New Jack Swing / R&B" },
    { "year": 1996, "title": "Don't Let Go (Love)", "artist": "En Vogue", "genre": "R&B / Soul" },
    { "year": 2000, "title": "Don't Mess With My Man", "artist": "Lucy Pearl", "genre": "R&B / Neo-Soul" },
    { "year": 1991, "title": "Finally", "artist": "CeCe Peniston", "genre": "Dance / House" },
    { "year": 2000, "title": "He Wasn't Man Enough", "artist": "Toni Braxton", "genre": "R&B / Pop" },
    { "year": 1982, "title": "How Come U Don't Call Me Anymore?", "artist": "Prince", "genre": "R&B / Soul" },
    { "year": 1985, "title": "How Will I Know", "artist": "Whitney Houston", "genre": "Pop / R&B" },
    { "year": 1984, "title": "I Feel For You", "artist": "Chaka Khan", "genre": "Funk / R&B" },
    { "year": 1993, "title": "I Have Nothing", "artist": "Whitney Houston", "genre": "Pop / R&B Ballad" },
  { "year": 1992, "title": "I Will Always Love You", "artist": "Whitney Houston", "genre": "Pop / R&B Ballad" },
    { "year": 1998, "title": "My Love Is Your Love", "artist": "Whitney Houston", "genre": "R&B / Reggae Fusion" },
    { "year": 1981, "title": "Never Too Much", "artist": "Luther Vandross", "genre": "R&B / Soul" },
    { "year": 1985, "title": "Saving All My Love for You", "artist": "Whitney Houston", "genre": "R&B / Soul" },
    { "year": 1986, "title": "Sweet Love", "artist": "Anita Baker", "genre": "R&B / Quiet Storm" },
    { "year": 1975, "title": "Sweet Thing", "artist": "Chaka Khan", "genre": "Soul / R&B" },
    { "year": 1996, "title": "Un-Break My Heart", "artist": "Toni Braxton", "genre": "Pop / R&B Ballad" },
  { "year": 2008, "title": "American Boy", "artist": "Estelle ft. Kanye West", "genre": "R&B / Hip Hop" },
    { "year": 2002, "title": "Boogie 2nite", "artist": "Tweet", "genre": "R&B / Neo-Soul" },
    { "year": 2003, "title": "Crazy In Love", "artist": "Beyoncé ft. Jay-Z", "genre": "R&B / Hip Hop" },
    { "year": 2006, "title": "Déjà Vu", "artist": "Beyoncé ft. Jay-Z", "genre": "R&B / Hip Hop" },
    { "year": 1998, "title": "Doo Wop (That Thing)", "artist": "Lauryn Hill", "genre": "R&B / Neo-Soul" },
    { "year": 2009, "title": "Empire State of Mind", "artist": "Alicia Keys ft. Jay-Z", "genre": "R&B / Hip Hop" },
    { "year": 1998, "title": "Ex-Factor", "artist": "Lauryn Hill", "genre": "R&B / Neo-Soul" },
    { "year": 2003, "title": "Hey Ya!", "artist": "OutKast", "genre": "Hip Hop / Funk" },
    { "year": 2004, "title": "Ignition (Remix)", "artist": "R. Kelly", "genre": "R&B / Hip Hop Soul" },
    { "year": 2002, "title": "Jenny From The Block", "artist": "Jennifer Lopez", "genre": "Pop / R&B" },
   { "year": 1996, "title": "No Diggity", "artist": "Blackstreet feat. Dr. Dre & Queen Pen", "genre": "R&B / Hip Hop" },
    { "year": 1996, "title": "Pony", "artist": "Ginuwine", "genre": "R&B" },
    { "year": 2009, "title": "Rude Boy", "artist": "Rihanna", "genre": "R&B / Dancehall" },
    { "year": 2011, "title": "Run The World (Girls)", "artist": "Beyoncé", "genre": "Pop / R&B" },
    { "year": 2006, "title": "SexyBack", "artist": "Justin Timberlake", "genre": "Electropop / R&B" },
    { "year": 1995, "title": "This Is How We Do It", "artist": "Montell Jordan", "genre": "R&B / Hip Hop" },
    { "year": 1998, "title": "To Zion", "artist": "Lauryn Hill", "genre": "Neo-Soul / Hip Hop" },
    { "year": 1996, "title": "Don't Let Go (Love)", "artist": "En Vogue", "genre": "R&B" },
  { "year": 2000, "title": "Don't Mess With My Man", "artist": "Lucy Pearl", "genre": "R&B / Funk" },
  { "year": 1989, "title": "(Simply) The Best", "artist": "Tina Turner", "genre": "Pop / Rock" },
    { "year": 1967, "title": "(You Make Me Feel Like) A Natural Woman", "artist": "Aretha Franklin", "genre": "Soul" },
    { "year": 1967, "title": "(Your Love Keeps Lifting Me) Higher and Higher", "artist": "Jackie Wilson", "genre": "R&B / Soul" },
    { "year": 1984, "title": "Ain't Nobody", "artist": "Chaka Khan", "genre": "R&B / Funk" },
    { "year": 1967, "title": "Ain't No Mountain High Enough", "artist": "Marvin Gaye & Tammi Terrell", "genre": "Motown / Soul" },
    { "year": 1979, "title": "Ain't No Stopping Us Now", "artist": "McFadden & Whitehead", "genre": "Disco / R&B" },
    { "year": 2000, "title": "A Long Walk", "artist": "Jill Scott", "genre": "Neo-Soul" },
    { "year": 1976, "title": "As", "artist": "Stevie Wonder", "genre": "Funk / Soul" },
    { "year": 1960, "title": "At Last", "artist": "Etta James", "genre": "Blues / Soul" },
    { "year": 1964, "title": "Baby Love", "artist": "The Supremes", "genre": "Motown / Soul" },
    { "year": 1963, "title": "Be My Baby", "artist": "The Ronettes", "genre": "Girl Group Pop" },
    { "year": 1977, "title": "Best Of My Love", "artist": "The Emotions", "genre": "Disco / R&B" },
    { "year": 1964, "title": "Can't Hurry Love", "artist": "The Supremes", "genre": "Motown Pop" },
    { "year": 1967, "title": "Chain Of Fools", "artist": "Aretha Franklin", "genre": "Soul" },
    { "year": 1976, "title": "Chain Reaction", "artist": "Diana Ross", "genre": "Disco / R&B" },
  { "year": 1964, "title": "Dancing In The Street", "artist": "Martha and The Vandellas", "genre": "Motown / Soul" },
    { "year": 1976, "title": "Disco Inferno", "artist": "The Trammps", "genre": "Disco" },
    { "year": 1962, "title": "Do You Love Me (Now That I Can Dance)", "artist": "The Contours", "genre": "Motown / R&B" },
    { "year": 1968, "title": "For Once In My Life", "artist": "Stevie Wonder", "genre": "Soul" },
    { "year": 1960, "title": "Georgia On My Mind", "artist": "Ray Charles", "genre": "Soul / Jazz" },
    { "year": 1966, "title": "Get Ready", "artist": "The Temptations", "genre": "Motown / Soul" },
    { "year": 1980, "title": "Happy Birthday", "artist": "Stevie Wonder", "genre": "Soul / Pop" },
    { "year": 1963, "title": "Heatwave", "artist": "Martha and The Vandellas", "genre": "Motown / Soul" },
    { "year": 1973, "title": "Higher Ground", "artist": "Stevie Wonder", "genre": "Funk / Soul" },
    { "year": 1961, "title": "Hit The Road Jack", "artist": "Ray Charles", "genre": "R&B / Soul" },
    { "year": 1992, "title": "I'm Every Woman", "artist": "Whitney Houston", "genre": "R&B / Dance-Pop" },
    { "year": 1984, "title": "I Feel For You", "artist": "Chaka Khan", "genre": "R&B / Funk" },
    { "year": 1965, "title": "I Got You (I Feel Good)", "artist": "James Brown", "genre": "Funk / Soul" },
    { "year": 1968, "title": "I Heard It Through The Grapevine", "artist": "Marvin Gaye", "genre": "Soul" },
    { "year": 1960, "title": "I Just Wanna Make Love To You", "artist": "Etta James", "genre": "Blues / Soul" },
   { "year": 1967, "title": "I Say A Little Prayer", "artist": "Dionne Warwick", "genre": "Soul / Pop" },
    { "year": 1976, "title": "Isn't She Lovely", "artist": "Stevie Wonder", "genre": "Soul / R&B" },
    { "year": 1966, "title": "It Takes Two", "artist": "Marvin Gaye", "genre": "Motown / Soul" },
    { "year": 1976, "title": "I Wish", "artist": "Stevie Wonder", "genre": "Funk / Soul" },
    { "year": 1978, "title": "I'm Every Woman", "artist": "Chaka Khan", "genre": "Disco / R&B" },
    { "year": 1967, "title": "Jimmy Mack", "artist": "Martha Reeves & The Vandellas", "genre": "Motown / Soul" },
    { "year": 1976, "title": "Knocks Me Off My Feet", "artist": "Stevie Wonder", "genre": "Soul / R&B" },
    { "year": 1974, "title": "Lady Marmalade", "artist": "Patti LaBelle", "genre": "Funk / Soul" },
    { "year": 1972, "title": "Lean On Me", "artist": "Bill Withers", "genre": "Soul" },
    { "year": 1973, "title": "Let's Get It On", "artist": "Marvin Gaye", "genre": "Soul" },
    { "year": 1972, "title": "Love Train", "artist": "The O'Jays", "genre": "R&B / Soul" },
    { "year": 2008, "title": "Mercy", "artist": "Duffy", "genre": "Soul / Pop" },
    { "year": 1991, "title": "Mustang Sally", "artist": "The Commitments", "genre": "Soul / Rock" },
    { "year": 1966, "title": "Mustang Sally", "artist": "Wilson Pickett", "genre": "R&B / Soul" },
  { "year": 1964, "title": "My Girl", "artist": "The Temptations", "genre": "Motown / Soul" },
  { "year": 1964, "title": "My Guy", "artist": "Mary Wells", "genre": "Motown / Soul" },
    { "year": 1967, "title": "Natural Woman", "artist": "Aretha Franklin", "genre": "Soul" },
    { "year": 1964, "title": "Needle In A Haystack", "artist": "The Velvelettes", "genre": "Motown / Soul" },
    { "year": 1965, "title": "Nowhere To Run", "artist": "Martha Reeves & The Vandellas", "genre": "Motown / Soul" },
    { "year": 1973, "title": "Nutbush City Limits", "artist": "Tina Turner", "genre": "Rock / Soul" },
    { "year": 1972, "title": "Papa Was A Rollin' Stone", "artist": "The Temptations", "genre": "Psychedelic Soul" },
    { "year": 1961, "title": "Please Mr. Postman", "artist": "The Marvelettes", "genre": "Motown / Soul" },
    { "year": 1969, "title": "Proud Mary", "artist": "Tina Turner", "genre": "Soul / Rock" },
    { "year": 1966, "title": "Reach Out I'll Be There", "artist": "Four Tops", "genre": "Motown / Soul" },
    { "year": 1965, "title": "Rescue Me", "artist": "Fontella Bass", "genre": "Soul" },
    { "year": 1967, "title": "Respect", "artist": "Aretha Franklin", "genre": "Soul" },
    { "year": 1969, "title": "River Deep - Mountain High", "artist": "Tina Turner", "genre": "Soul / Rock" },
    { "year": 1968, "title": "Say A Little Prayer", "artist": "Dionne Warwick", "genre": "Soul / Pop" },
    { "year": 1970, "title": "Signed, Sealed, Delivered I'm Yours", "artist": "Stevie Wonder", "genre": "Motown / Soul" },
    { "year": 1970, "title": "Sir Duke", "artist": "Stevie Wonder", "genre": "Funk / Soul" },
  { "year": 1984, "title": "Somebody Else's Guy", "artist": "Jocelyn Brown", "genre": "R&B / Soul" },
    { "year": 1968, "title": "Son of a Preacher Man", "artist": "Dusty Springfield", "genre": "Soul" },
    { "year": 1961, "title": "Stand By Me", "artist": "Ben E. King", "genre": "Soul" },
    { "year": 1965, "title": "Stop! In the Name of Love", "artist": "The Supremes", "genre": "Motown / Soul" },
    { "year": 1972, "title": "Superstition", "artist": "Stevie Wonder", "genre": "Funk / Soul" },
    { "year": 1989, "title": "The Best", "artist": "Tina Turner", "genre": "Rock / Pop" },
    { "year": 1968, "title": "Think", "artist": "Aretha Franklin", "genre": "Soul" },
    { "year": 1980, "title": "Upside Down", "artist": "Diana Ross", "genre": "Disco / Funk" },
    { "year": 1971, "title": "What's Going On", "artist": "Marvin Gaye", "genre": "Soul" },
    { "year": 1964, "title": "Where Did Our Love Go", "artist": "The Supremes", "genre": "Motown / Soul" },
    { "year": 1968, "title": "You're All I Need to Get By", "artist": "Marvin Gaye & Tammi Terrell", "genre": "Soul" },
    { "year": 1966, "title": "You Can't Hurry Love", "artist": "The Supremes", "genre": "Motown / Soul" },
    { "year": 1966, "title": "You Keep Me Hangin' On", "artist": "The Supremes", "genre": "Motown / Soul" },
    { "year": 1957, "title": "You Send Me", "artist": "Aretha Franklin", "genre": "Soul" },
  { "year": 1979, "title": "Bad Girls", "artist": "Donna Summer", "genre": "Disco" },
    { "year": 1978, "title": "Blame It On The Boogie", "artist": "The Jackson 5", "genre": "Disco / Funk" },
    { "year": 1978, "title": "Boogie Oogie Oogie", "artist": "A Taste Of Honey", "genre": "Disco / Funk" },
    { "year": 1986, "title": "Candy", "artist": "Cameo", "genre": "Funk / R&B" },
    { "year": 1976, "title": "Car Wash", "artist": "Rose Royce", "genre": "Funk / Disco" },
    { "year": 1980, "title": "Celebration", "artist": "Kool and The Gang", "genre": "Funk / Disco" },
    { "year": 1976, "title": "Disco Inferno", "artist": "The Trammps", "genre": "Disco" },
    { "year": 1978, "title": "Everybody Dance", "artist": "Chic", "genre": "Disco / Funk" },
    { "year": 1981, "title": "Get Down on It", "artist": "Kool And The Gang", "genre": "Funk" },
    { "year": 1979, "title": "Good Times", "artist": "Chic", "genre": "Disco / Funk" },
    { "year": 1979, "title": "Hot Stuff", "artist": "Donna Summer", "genre": "Disco / Rock" },
    { "year": 1980, "title": "I'm Coming Out", "artist": "Diana Ross", "genre": "Dance-Pop / Disco" },
    { "year": 1982, "title": "I'm So Excited", "artist": "The Pointer Sisters", "genre": "Dance / Pop" },
    { "year": 1965, "title": "I Got You (I Feel Good)", "artist": "James Brown", "genre": "Funk / Soul" },
    { "year": 1978, "title": "I Want Your Love", "artist": "Chic", "genre": "Disco / Funk" },
  { "year": 1978, "title": "I Will Survive", "artist": "Gloria Gaynor", "genre": "Disco" },
    { "year": 1979, "title": "Ladies Night", "artist": "Kool and The Gang", "genre": "Funk / Disco" },
    { "year": 1978, "title": "Le Freak", "artist": "Chic", "genre": "Disco" },
    { "year": 1979, "title": "Lost In Music", "artist": "Sister Sledge", "genre": "Disco / Funk" },
    { "year": 1975, "title": "Mamma Mia", "artist": "ABBA", "genre": "Pop / Disco" },
    { "year": 2000, "title": "Not That Kind", "artist": "Anastacia", "genre": "Pop / Soul" },
    { "year": 1979, "title": "On the Radio", "artist": "Donna Summer", "genre": "Disco" },
    { "year": 1976, "title": "Play That Funky Music", "artist": "Wild Cherry", "genre": "Funk / Rock" },
    { "year": 1978, "title": "September", "artist": "Earth, Wind & Fire", "genre": "Funk / Disco" },
    { "year": 1979, "title": "Thinking Of You", "artist": "Sister Sledge", "genre": "R&B / Disco" },
    { "year": 1980, "title": "Upside Down", "artist": "Diana Ross", "genre": "Disco / R&B" },
    { "year": 1979, "title": "We Are Family", "artist": "Sister Sledge", "genre": "Disco" },
    { "year": 1986, "title": "Word Up", "artist": "Cameo", "genre": "Funk / R&B" },
    { "year": 1981, "title": "You Might Need Somebody", "artist": "Randy Crawford", "genre": "Soul / R&B" },
  { "year": 2016, "title": "24K Magic", "artist": "Bruno Mars", "genre": "Funk Pop" },
    { "year": 2014, "title": "All About That Bass", "artist": "Meghan Trainor", "genre": "Pop" },
    { "year": 2011, "title": "The A Team", "artist": "Ed Sheeran", "genre": "Folk Pop" },
    { "year": 2014, "title": "Bang Bang", "artist": "Jessie J ft. Ariana Grande & Nicki Minaj", "genre": "Pop" },
    { "year": 2017, "title": "Be the One", "artist": "Dua Lipa", "genre": "Pop" },
    { "year": 2013, "title": "Blurred Lines", "artist": "Robin Thicke ft. Pharrell Williams", "genre": "R&B Pop" },
    { "year": 2001, "title": "Can't Get You Out of My Head", "artist": "Kylie Minogue", "genre": "Dance Pop" },
    { "year": 2016, "title": "Can't Stop the Feeling!", "artist": "Justin Timberlake", "genre": "Pop" },
    { "year": 2016, "title": "Cheap Thrills", "artist": "Sia", "genre": "Pop" },
    { "year": 2008, "title": "Cold Shoulder", "artist": "Adele", "genre": "R&B Pop" },
    { "year": 2006, "title": "Crazy", "artist": "Gnarls Barkley", "genre": "Soul Pop" },
    { "year": 2012, "title": "Diamonds", "artist": "Rihanna", "genre": "Pop" },
    { "year": 2010, "title": "Do It Like a Dude", "artist": "Jessie J", "genre": "Pop" },
    { "year": 2001, "title": "Don't Stop Movin'", "artist": "S Club 7", "genre": "Pop" },
    { "year": 2007, "title": "Don't Stop the Music", "artist": "Rihanna", "genre": "Pop Dance" },
  { "year": 1997, "title": "Everybody (Backstreet's Back)", "artist": "Backstreet Boys", "genre": "Pop" },
    { "year": 2018, "title": "Finesse", "artist": "Bruno Mars", "genre": "Funk Pop" },
    { "year": 2010, "title": "Firework", "artist": "Katy Perry", "genre": "Pop" },
    { "year": 2010, "title": "Forget You", "artist": "Cee Lo Green", "genre": "Soul Pop" },
    { "year": 2013, "title": "Get Lucky", "artist": "Daft Punk ft. Pharrell Williams", "genre": "Funk" },
    { "year": 2001, "title": "Get the Party Started", "artist": "Pink", "genre": "Pop Rock" },
    { "year": 2010, "title": "Grenade", "artist": "Bruno Mars", "genre": "Pop" },
    { "year": 2013, "title": "Happy", "artist": "Pharrell Williams", "genre": "Soul Pop" },
    { "year": 2017, "title": "Havana", "artist": "Camila Cabello", "genre": "Pop Latin" },
    { "year": 2000, "title": "I'm Outta Love", "artist": "Anastacia", "genre": "Pop Rock" },
    { "year": 2019, "title": "Juice", "artist": "Lizzo", "genre": "Funk Pop" },
    { "year": 1999, "title": "Livin' la Vida Loca", "artist": "Ricky Martin", "genre": "Latin Pop" },
    { "year": 2012, "title": "Locked Out of Heaven", "artist": "Bruno Mars", "genre": "Pop Rock" },
    { "year": 2015, "title": "Love Yourself", "artist": "Justin Bieber", "genre": "Pop" },
    { "year": 2008, "title": "Make You Feel My Love", "artist": "Adele", "genre": "Pop Ballad" },
  { "year": 2011, "title": "Moves Like Jagger", "artist": "Maroon 5 ft. Christina Aguilera", "genre": "Dance Pop" },
    { "year": 1995, "title": "Mysterious Girl", "artist": "Peter Andre", "genre": "Reggae Fusion" },
    { "year": 2017, "title": "New Rules", "artist": "Dua Lipa", "genre": "Electropop" },
    { "year": 2010, "title": "Only Girl (In the World)", "artist": "Rihanna", "genre": "Dance Pop" },
    { "year": 2005, "title": "Ordinary People", "artist": "John Legend", "genre": "R&B" },
    { "year": 2016, "title": "Perm", "artist": "Bruno Mars", "genre": "Funk" },
    { "year": 2014, "title": "Photograph", "artist": "Ed Sheeran", "genre": "Pop Ballad" },
    { "year": 2007, "title": "Don't Stop the Music", "artist": "Rihanna", "genre": "Dance Pop" },
    { "year": 2011, "title": "Price Tag", "artist": "Jessie J", "genre": "Pop" },
    { "year": 2006, "title": "Put Your Records On", "artist": "Corinne Bailey Rae", "genre": "Neo Soul" },
    { "year": 2014, "title": "Rather Be", "artist": "Clean Bandit ft. Jess Glynne", "genre": "Electropop" },
    { "year": 2000, "title": "Reach", "artist": "S Club 7", "genre": "Pop" },
    { "year": 2013, "title": "Roar", "artist": "Katy Perry", "genre": "Pop" },
    { "year": 2010, "title": "Rolling in the Deep", "artist": "Adele", "genre": "Soul Pop" },
    { "year": 2014, "title": "Shake It Off", "artist": "Taylor Swift", "genre": "Pop" },
   { "year": 2017, "title": "Shape of You", "artist": "Ed Sheeran", "genre": "Pop" },
    { "year": 2000, "title": "Spinning Around", "artist": "Kylie Minogue", "genre": "Dance Pop" },
    { "year": 1998, "title": "Stop", "artist": "Spice Girls", "genre": "Pop" },
    { "year": 2014, "title": "Thinking Out Loud", "artist": "Ed Sheeran", "genre": "Pop Ballad" },
    { "year": 2016, "title": "This Is What You Came For", "artist": "Calvin Harris feat. Rihanna", "genre": "EDM" },
    { "year": 2004, "title": "This Love", "artist": "Maroon 5", "genre": "Pop Rock" },
    { "year": 2003, "title": "Toxic", "artist": "Britney Spears", "genre": "Electropop" },
    { "year": 2012, "title": "Treasure", "artist": "Bruno Mars", "genre": "Funk Pop" },
    { "year": 2007, "title": "Umbrella", "artist": "Rihanna", "genre": "R&B" },
    { "year": 2014, "title": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars", "genre": "Funk Pop" },
    { "year": 2007, "title": "Valerie", "artist": "Mark Ronson ft. Amy Winehouse", "genre": "Soul" },
    { "year": 2013, "title": "Waiting All Night", "artist": "Rudimental ft. Ella Eyre", "genre": "Drum and Bass" },
    { "year": 1996, "title": "Wannabe", "artist": "Spice Girls", "genre": "Pop" },
    { "year": 2011, "title": "We Found Love", "artist": "Rihanna", "genre": "Dance Pop" },
    { "year": 2010, "title": "What's My Name?", "artist": "Rihanna", "genre": "Electropop" },
  { "year": 2003, "title": "Work It Out", "artist": "Beyoncé", "genre": "Funk" },
    { "year": 2007, "title": "Work", "artist": "Rihanna", "genre": "R&B" },
    { "year": 2008, "title": "You've Got the Love", "artist": "Florence + The Machine", "genre": "Indie Pop" },
    { "year": 2006, "title": "You Give Me Something", "artist": "James Morrison", "genre": "Soul Pop" },
  { "year": 1983, "title": "All Night Long (All Night)", "artist": "Lionel Richie", "genre": "Pop / R&B" },
    { "year": 1982, "title": "Billie Jean", "artist": "Michael Jackson", "genre": "Pop" },
    { "year": 1980, "title": "Can You Feel It", "artist": "The Jacksons", "genre": "Disco / Funk" },
    { "year": 1979, "title": "Don't Stop 'Til You Get Enough", "artist": "Michael Jackson", "genre": "Disco / Funk" },
    { "year": 1977, "title": "Easy", "artist": "Lionel Richie & Commodores", "genre": "Soft Rock / Soul" },
    { "year": 1970, "title": "I'll Be There", "artist": "The Jackson 5", "genre": "Pop / Soul" },
    { "year": 1982, "title": "It's Raining Men", "artist": "The Weather Girls", "genre": "Dance / Hi-NRG" },
    { "year": 1987, "title": "I Wanna Dance with Somebody (Who Loves Me)", "artist": "Whitney Houston", "genre": "Pop" },
    { "year": 1969, "title": "I Want You Back", "artist": "The Jackson 5", "genre": "Motown / Soul" },
    { "year": 1986, "title": "Kiss", "artist": "Prince", "genre": "Funk / Pop" },
    { "year": 1971, "title": "Never Can Say Goodbye", "artist": "The Jackson 5", "genre": "Soul / Disco" },
    { "year": 1981, "title": "Never Too Much", "artist": "Luther Vandross", "genre": "R&B / Soul" },
    { "year": 2002, "title": "Over the Rainbow", "artist": "Eva Cassidy", "genre": "Folk / Jazz" },
    { "year": 1983, "title": "P.Y.T. (Pretty Young Thing)", "artist": "Michael Jackson", "genre": "Pop" },
    { "year": 1993, "title": "Queen of the Night", "artist": "Whitney Houston", "genre": "R&B / Pop" },
  { "year": 1979, "title": "Rock with You", "artist": "Michael Jackson", "genre": "Disco / Pop" },
    { "year": 1978, "title": "Shake Your Body (Down to the Ground)", "artist": "The Jacksons", "genre": "Disco / Funk" },
    { "year": 1970, "title": "The Love You Save", "artist": "The Jackson 5", "genre": "Soul / Pop" },
    { "year": 1987, "title": "The Way You Make Me Feel", "artist": "Michael Jackson", "genre": "Pop / R&B" },
    { "year": 1984, "title": "When Doves Cry", "artist": "Prince", "genre": "Pop / Rock" },
    { "year": 1976, "title": "Young Hearts Run Free", "artist": "Candi Staton", "genre": "Disco / Soul" },
  { "year": 1980, "title": "Back In Black", "artist": "AC/DC", "genre": "Rock" },
    { "year": 1969, "title": "Come Together", "artist": "The Beatles", "genre": "Rock" },
    { "year": 1996, "title": "Don't Speak", "artist": "No Doubt", "genre": "Pop Rock" },
    { "year": 1996, "title": "Ironic", "artist": "Alanis Morissette", "genre": "Alt Rock" },
    { "year": 1999, "title": "Maria Maria", "artist": "Santana", "genre": "Latin Rock" },
    { "year": 1968, "title": "Piece Of My Heart", "artist": "Janis Joplin", "genre": "Rock / Blues Rock" },
    { "year": 2008, "title": "Sex on Fire", "artist": "Kings Of Leon", "genre": "Rock" },
    { "year": 1987, "title": "Sweet Child O' Mine", "artist": "Guns N' Roses", "genre": "Hard Rock" },
    { "year": 2008, "title": "Use Somebody", "artist": "Kings Of Leon", "genre": "Rock" },
    { "year": 1995, "title": "Wonderwall", "artist": "Oasis", "genre": "Britpop" },
    { "year": 1978, "title": "Is This Love", "artist": "Bob Marley", "genre": "Reggae" },
    { "year": 1977, "title": "Jammin'", "artist": "Bob Marley", "genre": "Reggae" },
    { "year": 2010, "title": "The Lazy Song", "artist": "Bruno Mars", "genre": "Pop Reggae" },
    { "year": 1980, "title": "Master Blaster (Jammin')", "artist": "Stevie Wonder", "genre": "Funk / Reggae Fusion" },
    { "year": 1974, "title": "No Woman, No Cry", "artist": "Bob Marley", "genre": "Reggae" },
    { "year": 1977, "title": "One Love", "artist": "Bob Marley", "genre": "Reggae" },
    { "year": 1980, "title": "Three Little Birds", "artist": "Bob Marley", "genre": "Reggae" },
    { "year": 1977, "title": "Turn Your Lights Down Low", "artist": "Bob Marley", "genre": "Reggae" },
    { "year": 2000, "title": "By Your Side", "artist": "Sade", "genre": "Soul / R&B" },
    { "year": 1965, "title": "Feeling Good", "artist": "Nina Simone", "genre": "Jazz / Soul" },
    { "year": 1958, "title": "Fever", "artist": "Peggy Lee", "genre": "Jazz / Pop" },
    { "year": 1964, "title": "Fly Me To The Moon", "artist": "Frank Sinatra", "genre": "Jazz Standard" },
    { "year": 2004, "title": "Golden", "artist": "Jill Scott", "genre": "Neo Soul" },
    { "year": 1985, "title": "The Sweetest Taboo", "artist": "Sade", "genre": "Smooth Jazz / Soul" },
    { "year": 1982, "title": "Last Night a DJ Saved My Life", "artist": "Indeep", "genre": "Disco / Funk" },
   { "year": 2017, "title": "Came Here For Love", "artist": "Sigala ft. Ella Eyre", "genre": "Dance / House" },
    { "year": 1993, "title": "Moving On Up", "artist": "M People", "genre": "Dance / House" },
    { "year": 2004, "title": "Move Ya Body", "artist": "Nina Sky", "genre": "R&B / Dancehall" },
    { "year": 2001, "title": "Gotta Get Thru This", "artist": "Daniel Bedingfield", "genre": "UK Garage / Pop" },
    { "year": 2000, "title": "Flowers", "artist": "Sweet Female Attitude", "genre": "UK Garage" },
    { "year": 1971, "title": "Let's Stay Together", "artist": "Al Green", "genre": "Soul" },
    { "year": 2010, "title": "Just The Way You Are", "artist": "Bruno Mars", "genre": "Pop / R&B" },
    { "year": 2017, "title": "Perfect", "artist": "Ed Sheeran", "genre": "Pop" },
    { "year": 1961, "title": "Can't Help Falling in Love", "artist": "Elvis Presley", "genre": "Pop" },
    { "year": 2013, "title": "All of Me", "artist": "John Legend", "genre": "R&B / Soul" },
    { "year": 1998, "title": "Can't Take My Eyes Off of You", "artist": "Lauryn Hill", "genre": "R&B / Soul" },
    { "year": 1996, "title": "Always Be My Baby", "artist": "Mariah Carey", "genre": "Pop / R&B" },
    { "year": 1964, "title": "How Sweet It Is (To Be Loved by You)", "artist": "Marvin Gaye", "genre": "Soul" },
    { "year": 1996, "title": "Great Is Your Mercy", "artist": "Donnie McClurkin", "genre": "Gospel" },
    { "year": 1779, "title": "Amazing Grace", "artist": "Gospel Standard", "genre": "Gospel Hymn" },
   { "year": 2010, "title": "I Smile", "artist": "Kirk Franklin", "genre": "Gospel" },
    { "year": 2005, "title": "Imagine Me", "artist": "Kirk Franklin", "genre": "Gospel" },
    { "year": 2007, "title": "Never Would Have Made It", "artist": "Marvin Sapp", "genre": "Gospel" },
    { "year": 1993, "title": "Joyful Joyful", "artist": "Sister Act Cast", "genre": "Gospel / Musical" },
    { "year": 1969, "title": "Oh Happy Day", "artist": "Edwin Hawkins Singers", "genre": "Gospel" },
    { "year": 1942, "title": "White Christmas", "artist": "Bing Crosby", "genre": "Holiday / Jazz Standard" },
    { "year": 1985, "title": "Santa Claus Is Comin' to Town", "artist": "Bruce Springsteen", "genre": "Holiday / Rock" },
    { "year": 1994, "title": "All I Want for Christmas Is You", "artist": "Mariah Carey", "genre": "Holiday / Pop" },
    { "year": 1949, "title": "Rudolph the Red-Nosed Reindeer", "artist": "Gene Autry", "genre": "Holiday / Children's" },
  { "year": 2000, "title": "Re-Rewind (The Crowd Say Bo Selecta)", "artist": "Artful Dodger ft. Craig David", "genre": "UK Garage" },
    { "year": 2001, "title": "Gotta Get Through This", "artist": "Daniel Bedingfield", "genre": "UK Garage / Pop" },
    { "year": 2001, "title": "Do You Really Like It?", "artist": "DJ Pied Piper & The Master of Ceremonies", "genre": "UK Garage" },
    { "year": 2001, "title": "21 Seconds", "artist": "So Solid Crew", "genre": "UK Garage / Rap" },
    { "year": 2001, "title": "Sambuca", "artist": "Wideboys", "genre": "UK Garage / Dance" },
    { "year": 2003, "title": "In Da Club", "artist": "50 Cent", "genre": "Hip Hop" },
    { "year": 1997, "title": "Hypnotize", "artist": "The Notorious B.I.G.", "genre": "Hip Hop" },
    { "year": 2006, "title": "Mas Que Nada", "artist": "Black Eyed Peas", "genre": "Latin Pop / Hip Hop" },
    { "year": 1996, "title": "No Diggity", "artist": "Blackstreet feat. Dr. Dre & Queen Pen", "genre": "R&B / Hip Hop" },
    { "year": 1999, "title": "Still D.R.E.", "artist": "Dr. Dre ft. Snoop Dogg", "genre": "Hip Hop" },
    { "year": 2016, "title": "One Dance", "artist": "Drake", "genre": "Dancehall / Hip Hop" },
    { "year": 2008, "title": "American Boy", "artist": "Estelle ft. Kanye West", "genre": "R&B / Hip Hop" },
    { "year": 2001, "title": "Let Me Blow Ya Mind", "artist": "Eve ft. Gwen Stefani", "genre": "Hip Hop / R&B" },
    { "year": 2004, "title": "Tipsy", "artist": "J-Kwon", "genre": "Hip Hop" },
    { "year": 2003, "title": "Senorita", "artist": "Justin Timberlake", "genre": "Pop / R&B" },
   { "year": 2011, "title": "N**as in Paris", "artist": "Jay-Z & Kanye West", "genre": "Hip Hop" },
    { "year": 2020, "title": "Hold On", "artist": "Lil Tjay", "genre": "Hip Hop / R&B" },
    { "year": 2008, "title": "A Milli", "artist": "Lil Wayne", "genre": "Hip Hop" },
    { "year": 1999, "title": "Got Your Money", "artist": "Ol' Dirty Bastard ft. Kelis", "genre": "Hip Hop" },
    { "year": 2003, "title": "Roses", "artist": "OutKast", "genre": "Hip Hop / Funk" },
    { "year": 1999, "title": "Simon Says", "artist": "Pharoahe Monch", "genre": "Hip Hop" },
    { "year": 1995, "title": "I Wish", "artist": "Skee-Lo", "genre": "Hip Hop" },
    { "year": 2004, "title": "Drop It Like It's Hot", "artist": "Snoop Dogg", "genre": "Hip Hop" },
    { "year": 2004, "title": "Lean Back", "artist": "Terror Squad", "genre": "Hip Hop" },
    { "year": 1994, "title": "Big Poppa", "artist": "The Notorious B.I.G.", "genre": "Hip Hop" },
    { "year": 1997, "title": "Mo Money Mo Problems", "artist": "The Notorious B.I.G.", "genre": "Hip Hop" },
    { "year": 2005, "title": "Nasty Girl", "artist": "The Notorious B.I.G.", "genre": "Hip Hop" },
    { "year": 2003, "title": "Breathe", "artist": "Blu Cantrell ft. Sean Paul", "genre": "R&B / Dancehall" },
    { "year": 2003, "title": "Hey Ya!", "artist": "OutKast", "genre": "Funk / Pop" },
    { "year": 2018, "title": "What's The Use?", "artist": "Mac Miller", "genre": "Funk / Hip Hop" },
    { "year": 2014, "title": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars", "genre": "Funk / Pop" },
    { "year": 1966, "title": "I'm A Believer", "artist": "The Monkees", "genre": "Pop Rock" },
    { "year": 2012, "title": "Thinking About You", "artist": "Calvin Harris ft. Ayah Marar", "genre": "Dance / Electronic" },
    { "year": 2003, "title": "Stronger Than Me", "artist": "Amy Winehouse", "genre": "Jazz / Soul" },
    { "year": 2007, "title": "Valerie", "artist": "Mark Ronson ft. Amy Winehouse", "genre": "Soul / Funk" },
    { "year": 2014, "title": "Don't", "artist": "Ed Sheeran", "genre": "Pop / R&B" },
    { "year": 1993, "title": "Show Me Love", "artist": "Robin S", "genre": "House" },
    { "year": 2020, "title": "Still Your Best", "artist": "Giveon", "genre": "R&B" },
    { "year": 2015, "title": "How Deep Is Your Love", "artist": "Calvin Harris & Disciples", "genre": "Dance / Electronic" },
    { "year": 2015, "title": "Rumour Mill", "artist": "Rudimental ft. Anne-Marie & Will Heard", "genre": "Drum and Bass / Pop" },
    { "year": 1994, "title": "U Sure Do", "artist": "Strike", "genre": "House" },
    { "year": 2006, "title": "Crazy", "artist": "Gnarls Barkley", "genre": "Soul / Pop" },
    { "year": 2006, "title": "Smile", "artist": "Lily Allen", "genre": "Pop / Reggae Fusion" },
    { "year": 2016, "title": "Cold Water", "artist": "Major Lazer ft. Justin Bieber & MØ", "genre": "Dancehall / EDM" },
    { "year": 2021, "title": "Peaches", "artist": "Justin Bieber ft. Daniel Caesar & Giveon", "genre": "R&B / Pop" },
  { "year": 1997, "title": "Miami", "artist": "Will Smith", "genre": "Hip Hop / Pop" },
    { "year": 1999, "title": "U Know What's Up", "artist": "Donell Jones", "genre": "R&B" },
    { "year": 1995, "title": "I Got 5 On It", "artist": "Luniz", "genre": "Hip Hop" },
    { "year": 1995, "title": "This Is How We Do It", "artist": "Montell Jordan", "genre": "R&B / New Jack Swing" },
    { "year": 2001, "title": "Fallin'", "artist": "Alicia Keys", "genre": "R&B / Soul" },
    { "year": 2000, "title": "Rendezvous", "artist": "Craig David", "genre": "UK Garage / R&B" },
    { "year": 2015, "title": "White Tiger", "artist": "Izzy Bizu", "genre": "Indie Pop / Soul" },
    { "year": 2011, "title": "I Need", "artist": "Maverick Sabre", "genre": "Soul / Hip Hop" },
    { "year": 2019, "title": "Talk", "artist": "DJ Khaled ft. Jhené Aiko", "genre": "R&B" },
    { "year": 2014, "title": "Girls Love Beyoncé", "artist": "Drake ft. James Fauntleroy", "genre": "R&B" },
    { "year": 2021, "title": "Someone That You Love", "artist": "Jarreau Vandal", "genre": "Electronic / R&B" },
    { "year": 1999, "title": "No Scrubs", "artist": "TLC", "genre": "R&B / Pop" },
    { "year": 2004, "title": "Just A Friend 2002", "artist": "Mario", "genre": "R&B / Pop" },
    { "year": 1972, "title": "Superstition", "artist": "Stevie Wonder", "genre": "Funk / Soul" },
    { "year": 1978, "title": "Blame It On The Boogie", "artist": "The Jacksons", "genre": "Disco / Funk" },
    { "year": 1961, "title": "Stand By Me", "artist": "Ben E. King", "genre": "Soul / R&B" },
    { "year": 1971, "title": "Grandma's Hands", "artist": "Bill Withers", "genre": "Soul" },
    { "year": 1981, "title": "Never Too Much", "artist": "Luther Vandross", "genre": "R&B / Soul" },
    { "year": 1995, "title": "The Way You Look Tonight", "artist": "Michael Jackson", "genre": "Pop / Soul" },
    { "year": 1970, "title": "Signed, Sealed, Delivered I'm Yours", "artist": "Stevie Wonder", "genre": "Soul / Funk" },
    { "year": 1967, "title": "Can't Take My Eyes Off You", "artist": "Andy Williams", "genre": "Pop / Traditional Pop" },
    { "year": 1987, "title": "The Way You Make Me Feel", "artist": "Michael Jackson", "genre": "Pop / R&B" },
    { "year": 2000, "title": "Re-Rewind", "artist": "Artful Dodger ft. Craig David", "genre": "UK Garage" },
    { "year": 2001, "title": "Gotta Get Thru This", "artist": "Daniel Bedingfield", "genre": "UK Garage / Pop" },
    { "year": 2001, "title": "Do You Really Like It?", "artist": "DJ Pied Piper & The Masters of Ceremonies", "genre": "UK Garage" },
    { "year": 2001, "title": "21 Seconds", "artist": "So Solid Crew", "genre": "UK Garage / Rap" },
    { "year": 2001, "title": "Sambuca", "artist": "Wideboys", "genre": "UK Garage" },
    { "year": 2003, "title": "In Da Club", "artist": "50 Cent", "genre": "Hip Hop" },
    { "year": 1997, "title": "Hypnotize", "artist": "The Notorious B.I.G.", "genre": "Hip Hop / Rap" },
    { "year": 2006, "title": "Mas Que Nada", "artist": "Black Eyed Peas ft. Sérgio Mendes", "genre": "Latin Pop / Hip Hop" },
   { "year": 1996, "title": "No Diggity", "artist": "Blackstreet feat. Dr. Dre & Queen Pen", "genre": "R&B / Hip Hop" },
    { "year": 1999, "title": "Still D.R.E.", "artist": "Dr. Dre ft. Snoop Dogg", "genre": "Hip Hop" },
    { "year": 2016, "title": "One Dance", "artist": "Drake", "genre": "Afrobeats / Pop" },
    { "year": 2008, "title": "American Boy", "artist": "Estelle ft. Kanye West", "genre": "R&B / Pop" },
    { "year": 2001, "title": "Let Me Blow Ya Mind", "artist": "Eve ft. Gwen Stefani", "genre": "Hip Hop / R&B" },
    { "year": 2004, "title": "Tipsy", "artist": "J-Kwon", "genre": "Hip Hop" },
    { "year": 2002, "title": "Señorita", "artist": "Justin Timberlake", "genre": "Pop / R&B" },
    { "year": 2011, "title": "Ni**as In Paris", "artist": "Jay-Z & Kanye West", "genre": "Hip Hop" },
    { "year": 2020, "title": "Hold On", "artist": "Lil Tjay", "genre": "Hip Hop / Rap" },
    { "year": 2008, "title": "A Milli", "artist": "Lil Wayne", "genre": "Hip Hop" },
    { "year": 1999, "title": "Got Your Money", "artist": "Ol' Dirty Bastard ft. Kelis", "genre": "Hip Hop" },
    { "year": 2003, "title": "Roses", "artist": "OutKast", "genre": "Hip Hop / Funk" },
    { "year": 1999, "title": "Simon Says", "artist": "Pharoahe Monch", "genre": "Hip Hop" },
    { "year": 1995, "title": "I Wish", "artist": "Skee-Lo", "genre": "Hip Hop / Pop Rap" },
    { "year": 2004, "title": "Drop It Like It's Hot", "artist": "Snoop Dogg ft. Pharrell", "genre": "Hip Hop" },
    { "year": 2004, "title": "Lean Back", "artist": "Terror Squad", "genre": "Hip Hop" },
    { "year": 1994, "title": "Big Poppa", "artist": "The Notorious B.I.G.", "genre": "Hip Hop" },
    { "year": 1997, "title": "Mo Money Mo Problems", "artist": "The Notorious B.I.G.", "genre": "Hip Hop" },
    { "year": 2005, "title": "Nasty Girl", "artist": "The Notorious B.I.G.", "genre": "Hip Hop" },
    { "year": 2003, "title": "Breathe", "artist": "Blu Cantrell ft. Sean Paul", "genre": "R&B / Dancehall" },
    { "year": 2003, "title": "Hey Ya!", "artist": "OutKast", "genre": "Funk / Pop" },
    { "year": 2018, "title": "What's the Use?", "artist": "Mac Miller", "genre": "Funk / Hip Hop" },
    { "year": 2014, "title": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars", "genre": "Funk / Pop" },
    { "year": 1966, "title": "I'm a Believer", "artist": "The Monkees", "genre": "Pop Rock" },
    { "year": 2012, "title": "Thinking About You", "artist": "Calvin Harris ft. Ayah Marar", "genre": "Dance / Electronic" },
    { "year": 2003, "title": "Stronger Than Me", "artist": "Amy Winehouse", "genre": "Jazz / Soul" },
    { "year": 2007, "title": "Valerie", "artist": "Mark Ronson ft. Amy Winehouse", "genre": "Soul / Pop" },
    { "year": 2014, "title": "Don't", "artist": "Ed Sheeran", "genre": "Pop / R&B" },
    { "year": 1993, "title": "Show Me Love", "artist": "Robin S", "genre": "House" },
    { "year": 2020, "title": "Still Your Best", "artist": "Giveon", "genre": "R&B" },
   { "year": 2015, "title": "How Deep Is Your Love", "artist": "Calvin Harris & Disciples", "genre": "Dance / House" },
    { "year": 2015, "title": "Rumour Mill", "artist": "Rudimental ft. Anne-Marie & Will Heard", "genre": "Drum and Bass / Pop" },
    { "year": 1994, "title": "U Sure Do", "artist": "Strike", "genre": "Dance / House" },
    { "year": 2006, "title": "Crazy", "artist": "Gnarls Barkley", "genre": "Soul / Alternative" },
    { "year": 2006, "title": "Smile", "artist": "Lily Allen", "genre": "Pop / Reggae Fusion" },
    { "year": 2016, "title": "Cold Water", "artist": "Major Lazer ft. Justin Bieber & MØ", "genre": "Pop / EDM" },
    { "year": 2021, "title": "Peaches", "artist": "Justin Bieber ft. Daniel Caesar & Giveon", "genre": "R&B / Pop" },
    { "year": 1997, "title": "Miami", "artist": "Will Smith", "genre": "Hip Hop / Pop" },
    { "year": 1999, "title": "U Know What's Up", "artist": "Donell Jones", "genre": "R&B" },
    { "year": 1995, "title": "I Got 5 On It", "artist": "Luniz", "genre": "Hip Hop" },
    { "year": 1995, "title": "This Is How We Do It", "artist": "Montell Jordan", "genre": "R&B / New Jack Swing" },
    { "year": 2001, "title": "Fallin'", "artist": "Alicia Keys", "genre": "R&B / Soul" },
    { "year": 2000, "title": "Rendezvous", "artist": "Craig David", "genre": "UK Garage / R&B" },
    { "year": 2013, "title": "White Tiger", "artist": "Izzy Bizu", "genre": "Soul / Pop" },
    { "year": 2011, "title": "I Need", "artist": "Maverick Sabre", "genre": "R&B / Hip Hop" },
   { "year": 2019, "title": "Talk", "artist": "Khalid", "genre": "R&B / Pop" },
    { "year": 2014, "title": "Girls Love Beyoncé", "artist": "Drake ft. James Fauntleroy", "genre": "R&B / Hip Hop" },
    { "year": 2022, "title": "Someone That You Love", "artist": "Jarreau Vandal", "genre": "R&B / Electronic" },
    { "year": 1999, "title": "No Scrubs", "artist": "TLC", "genre": "R&B / Pop" },
    { "year": 2002, "title": "Just A Friend 2002", "artist": "Mario", "genre": "R&B" },
    { "year": 1972, "title": "Superstition", "artist": "Stevie Wonder", "genre": "Funk / Soul" },
    { "year": 1978, "title": "Blame It On The Boogie", "artist": "The Jacksons", "genre": "Disco / Funk" },
    { "year": 1961, "title": "Stand By Me", "artist": "Ben E. King", "genre": "Soul / R&B" },
    { "year": 1971, "title": "Grandma's Hands", "artist": "Bill Withers", "genre": "Soul / Gospel" },
    { "year": 1981, "title": "Never Too Much", "artist": "Luther Vandross", "genre": "R&B / Soul" },
    { "year": 1982, "title": "The Way You Make Me Feel", "artist": "Michael Jackson", "genre": "Pop / R&B" },
    { "year": 1970, "title": "Signed, Sealed, Delivered I'm Yours", "artist": "Stevie Wonder", "genre": "Soul / Funk" },
    { "year": 1967, "title": "Can't Take My Eyes Off You", "artist": "Andy Williams", "genre": "Pop / Easy Listening" },
    { "year": 1987, "title": "The Way You Make Me Feel", "artist": "Michael Jackson", "genre": "Pop / R&B" },
  ]
  
  