[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 8888
  framework = "vite"
  autoLaunch = false

# Lets you call /api/... in both dev and prod
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200